config/routes.rb
Rails.application.routes.draw do
  devise_for(:accounts)

  authenticate :account, ->(account) {account.administrator?} do
    mount(Flipper::UI.app(Flipper) => "/admin/flipper")
    mount(Sidekiq::Web => "/admin/sidekiq")
  end

  namespace :admin do
    root :to => "pages#admin"
  end

  get "/frontpage" => "pages#show", :as => :frontpage, :format => false, :id => "frontpage"
  get "/pages/*id" => "pages#show", :as => :page, :format => false

  root :to => "pages#show", :id => "landing"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/frontpage.html.erb
<% content_for :browser_title, "Iron - Frontpage" %>
<% content_for :page_header, "Frontpage" %>
<% content_for :page_types, :splash %>

<p>
  Welcome!
</p>

<section class="call-to-actions btn-group">
  <%= button_to("Sign out", destroy_account_session_path(), :method => :delete, data: {:confirm => "You sure?"}, :class => "btn btn-link link-primary") %>
</section>

app/views/pages/landing.html.erb
<% content_for :browser_title, "Iron" %>
<% content_for :page_header, "Iron" %>
<% content_for :page_types, :splash %>

<blockquote class="blockquote">
  <p>
    Welcome.
  </p>
</blockquote>

<section class="call-to-actions btn-group">
  <%= link_to "Sign up", new_account_registration_url(), class: "btn btn-link link-primary" %>
  <%= link_to "Login", new_account_session_url(), class: "btn btn-link link-primary" %>
</section>

<picture>
  <%= image_tag image_path("logo.png") %>
</picture>